version: "3"
services:
  motorway-takehome-api:
    image: motorway/motorway-takehome-api
    build: .
    environment:
      - PORT=3000
    depends_on:
      - db
      - redis
  db:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis
      
volumes:
  db-data: