version: "3"
services:
  motorway-takehome-api:
    build: 
      target: prod
      args: 
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST}   
      - CACHE_TTL=${CACHE_TTL}
    deploy:
      replicas: 2
    restart: always

  nginx:
    image: motorway/motorway-takehome-nginx
    build: 
      context: ./nginx
    ports:
      - "5000:5000"
    depends_on:
      - motorway-takehome-api
    environment:
      - NODE_ENV=production
    restart: always

  db:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}