version: "3"
services:
  motorway-takehome-api:
    build: 
      target: prod
      args: 
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 2
    restart: always

  nginx:
    image: motorway/motorway-takehome-nginx
    build: 
      context: ./nginx
    ports:
      - "5000:5000"
    depends_on:
      - motorway-takehome-api
    environment:
      - NODE_ENV=production
    restart: always

  db:
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=motorway