version: "3"
services:
  motorway-takehome-api:
    build: .
    environment:
      - PORT=3000
  db:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      
volumes:
  db-data:
    driver: local