version: "3"
services:
  motorway-takehome-api:
    container_name: tester
    build: 
      target: test
      context: .
      args: 
        NODE_ENV: development
    volumes: 
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"


  db:
    image: motorway-test-backend
    container_name: motorway-test-backend
    build:
      context: ./motorway-test-backend
      target: motorway-test-backend
      dockerfile: Dockerfile

    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=motorway
    ports:
      - 5432:5432