version: "3"
services:
  motorway-takehome-api:
    build: 
      context: .
      args: 
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 2

  nginx:
    build: 
      context: ./nginx
    ports:
      - "5000:5000"
    depends_on:
      - motorway-takehome-api
    environment:
      - NODE_ENV=production
