version: "3"

services:
  motorway-takehome-api:
    build: 
      target: dev
      context: .
      args: 
        NODE_ENV: development
    volumes: 
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CACHE_TTL=0
    ports:
      - "3000:3000"
    command: npm run dev


  db:
    image: motorway-test-backend
    container_name: motorway-test-backend
    build:
      context: ./motorway-test-backend
      target: motorway-test-backend
      dockerfile: Dockerfile

    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=motorway
    ports:
      - 5432:5432
